name: Deploy-job

on:
  push:
    branches: [ "master", "main", "develop" ]

jobs:
  hobs:
    runs-on: ubuntu-latest
    name: Deploy and run Docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew bootJar

      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: hzfarm.ru
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/libs/*.jar"
          target: "app"

      - name: run Docker on remote server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: hzfarm.ru
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          script: |
            set -e
            cd app
            
            docker compose down app
            
            docker compose up -d